import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/Providers";
import MenuData from "@/components/MenuData";
import {Toaster} from "@/components/ui/toaster";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    robots: 'noindex, nofollow'
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="en" className={'dark'}>
            <head>
                <script async src="https://telegram.org/js/telegram-web-app.js"></script>
            </head>
            <body
                className={`antialiased w-screen h-screen overflow-x-hidden`}
            >
                <Providers>
                    <Toaster/>
                    <MenuData/>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
