import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/providers/Providers";
import Menu from "@/components/Menu";


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="en" className={'dark'}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen overflow-x-hidden`}
            >
                <Providers>
                    <Menu
                        bars={[
                            {
                                title: 'Categories',
                                items: [{title: 'Warface', shortcut: 'говно', path: 'warface'}],
                                path: 'category'
                            },
                            {
                                title: 'Profile',
                                items: [{title: 'Кошелек', shortcut: '2.3 TON', path: 'wallet'}],
                                path: 'profile'
                            }
                        ]}
                    />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
